// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

#ifndef PROTOBUF_stream_2eproto__INCLUDED
#define PROTOBUF_stream_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_stream_2eproto();
void protobuf_AssignDesc_stream_2eproto();
void protobuf_ShutdownFile_stream_2eproto();

class FrameRequest;
class FrameGroupRequest;
class FrameHeader;
class FrameResponse;
class FrameFragment;

enum FrameGroupRequest_RequestType {
  FrameGroupRequest_RequestType_Fetch = 0,
  FrameGroupRequest_RequestType_PriorityChanged = 1,
  FrameGroupRequest_RequestType_SetPrimaryFrame = 2,
  FrameGroupRequest_RequestType_Cancel = 3
};
bool FrameGroupRequest_RequestType_IsValid(int value);
const FrameGroupRequest_RequestType FrameGroupRequest_RequestType_RequestType_MIN = FrameGroupRequest_RequestType_Fetch;
const FrameGroupRequest_RequestType FrameGroupRequest_RequestType_RequestType_MAX = FrameGroupRequest_RequestType_Cancel;
const int FrameGroupRequest_RequestType_RequestType_ARRAYSIZE = FrameGroupRequest_RequestType_RequestType_MAX + 1;

const ::google::protobuf::EnumDescriptor* FrameGroupRequest_RequestType_descriptor();
inline const ::std::string& FrameGroupRequest_RequestType_Name(FrameGroupRequest_RequestType value) {
  return ::google::protobuf::internal::NameOfEnum(
    FrameGroupRequest_RequestType_descriptor(), value);
}
inline bool FrameGroupRequest_RequestType_Parse(
    const ::std::string& name, FrameGroupRequest_RequestType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FrameGroupRequest_RequestType>(
    FrameGroupRequest_RequestType_descriptor(), name, value);
}
enum FrameGroupRequest_Priority {
  FrameGroupRequest_Priority_Selected = 0,
  FrameGroupRequest_Priority_Visible = 1,
  FrameGroupRequest_Priority_Hidden = 2
};
bool FrameGroupRequest_Priority_IsValid(int value);
const FrameGroupRequest_Priority FrameGroupRequest_Priority_Priority_MIN = FrameGroupRequest_Priority_Selected;
const FrameGroupRequest_Priority FrameGroupRequest_Priority_Priority_MAX = FrameGroupRequest_Priority_Hidden;
const int FrameGroupRequest_Priority_Priority_ARRAYSIZE = FrameGroupRequest_Priority_Priority_MAX + 1;

const ::google::protobuf::EnumDescriptor* FrameGroupRequest_Priority_descriptor();
inline const ::std::string& FrameGroupRequest_Priority_Name(FrameGroupRequest_Priority value) {
  return ::google::protobuf::internal::NameOfEnum(
    FrameGroupRequest_Priority_descriptor(), value);
}
inline bool FrameGroupRequest_Priority_Parse(
    const ::std::string& name, FrameGroupRequest_Priority* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FrameGroupRequest_Priority>(
    FrameGroupRequest_Priority_descriptor(), name, value);
}
enum FrameHeader_bitDepth {
  FrameHeader_bitDepth_depthU8 = 0,
  FrameHeader_bitDepth_depthS8 = 1,
  FrameHeader_bitDepth_depthU16 = 2,
  FrameHeader_bitDepth_depthS16 = 3,
  FrameHeader_bitDepth_depthU32 = 4,
  FrameHeader_bitDepth_depthS32 = 5
};
bool FrameHeader_bitDepth_IsValid(int value);
const FrameHeader_bitDepth FrameHeader_bitDepth_bitDepth_MIN = FrameHeader_bitDepth_depthU8;
const FrameHeader_bitDepth FrameHeader_bitDepth_bitDepth_MAX = FrameHeader_bitDepth_depthS32;
const int FrameHeader_bitDepth_bitDepth_ARRAYSIZE = FrameHeader_bitDepth_bitDepth_MAX + 1;

const ::google::protobuf::EnumDescriptor* FrameHeader_bitDepth_descriptor();
inline const ::std::string& FrameHeader_bitDepth_Name(FrameHeader_bitDepth value) {
  return ::google::protobuf::internal::NameOfEnum(
    FrameHeader_bitDepth_descriptor(), value);
}
inline bool FrameHeader_bitDepth_Parse(
    const ::std::string& name, FrameHeader_bitDepth* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FrameHeader_bitDepth>(
    FrameHeader_bitDepth_descriptor(), name, value);
}
// ===================================================================

class FrameRequest : public ::google::protobuf::Message {
 public:
  FrameRequest();
  virtual ~FrameRequest();
  
  FrameRequest(const FrameRequest& from);
  
  inline FrameRequest& operator=(const FrameRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FrameRequest& default_instance();
  
  void Swap(FrameRequest* other);
  
  // implements Message ----------------------------------------------
  
  FrameRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FrameRequest& from);
  void MergeFrom(const FrameRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string instanceUid = 1;
  inline bool has_instanceuid() const;
  inline void clear_instanceuid();
  static const int kInstanceUidFieldNumber = 1;
  inline const ::std::string& instanceuid() const;
  inline void set_instanceuid(const ::std::string& value);
  inline void set_instanceuid(const char* value);
  inline void set_instanceuid(const char* value, size_t size);
  inline ::std::string* mutable_instanceuid();
  inline ::std::string* release_instanceuid();
  
  // required uint32 instanceUidNumber = 2;
  inline bool has_instanceuidnumber() const;
  inline void clear_instanceuidnumber();
  static const int kInstanceUidNumberFieldNumber = 2;
  inline ::google::protobuf::uint32 instanceuidnumber() const;
  inline void set_instanceuidnumber(::google::protobuf::uint32 value);
  
  // required uint32 frameNumber = 3;
  inline bool has_framenumber() const;
  inline void clear_framenumber();
  static const int kFrameNumberFieldNumber = 3;
  inline ::google::protobuf::uint32 framenumber() const;
  inline void set_framenumber(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:Protocol.FrameRequest)
 private:
  inline void set_has_instanceuid();
  inline void clear_has_instanceuid();
  inline void set_has_instanceuidnumber();
  inline void clear_has_instanceuidnumber();
  inline void set_has_framenumber();
  inline void clear_has_framenumber();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* instanceuid_;
  ::google::protobuf::uint32 instanceuidnumber_;
  ::google::protobuf::uint32 framenumber_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_stream_2eproto();
  friend void protobuf_AssignDesc_stream_2eproto();
  friend void protobuf_ShutdownFile_stream_2eproto();
  
  void InitAsDefaultInstance();
  static FrameRequest* default_instance_;
};
// -------------------------------------------------------------------

class FrameGroupRequest : public ::google::protobuf::Message {
 public:
  FrameGroupRequest();
  virtual ~FrameGroupRequest();
  
  FrameGroupRequest(const FrameGroupRequest& from);
  
  inline FrameGroupRequest& operator=(const FrameGroupRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FrameGroupRequest& default_instance();
  
  void Swap(FrameGroupRequest* other);
  
  // implements Message ----------------------------------------------
  
  FrameGroupRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FrameGroupRequest& from);
  void MergeFrom(const FrameGroupRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef FrameGroupRequest_RequestType RequestType;
  static const RequestType Fetch = FrameGroupRequest_RequestType_Fetch;
  static const RequestType PriorityChanged = FrameGroupRequest_RequestType_PriorityChanged;
  static const RequestType SetPrimaryFrame = FrameGroupRequest_RequestType_SetPrimaryFrame;
  static const RequestType Cancel = FrameGroupRequest_RequestType_Cancel;
  static inline bool RequestType_IsValid(int value) {
    return FrameGroupRequest_RequestType_IsValid(value);
  }
  static const RequestType RequestType_MIN =
    FrameGroupRequest_RequestType_RequestType_MIN;
  static const RequestType RequestType_MAX =
    FrameGroupRequest_RequestType_RequestType_MAX;
  static const int RequestType_ARRAYSIZE =
    FrameGroupRequest_RequestType_RequestType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RequestType_descriptor() {
    return FrameGroupRequest_RequestType_descriptor();
  }
  static inline const ::std::string& RequestType_Name(RequestType value) {
    return FrameGroupRequest_RequestType_Name(value);
  }
  static inline bool RequestType_Parse(const ::std::string& name,
      RequestType* value) {
    return FrameGroupRequest_RequestType_Parse(name, value);
  }
  
  typedef FrameGroupRequest_Priority Priority;
  static const Priority Selected = FrameGroupRequest_Priority_Selected;
  static const Priority Visible = FrameGroupRequest_Priority_Visible;
  static const Priority Hidden = FrameGroupRequest_Priority_Hidden;
  static inline bool Priority_IsValid(int value) {
    return FrameGroupRequest_Priority_IsValid(value);
  }
  static const Priority Priority_MIN =
    FrameGroupRequest_Priority_Priority_MIN;
  static const Priority Priority_MAX =
    FrameGroupRequest_Priority_Priority_MAX;
  static const int Priority_ARRAYSIZE =
    FrameGroupRequest_Priority_Priority_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Priority_descriptor() {
    return FrameGroupRequest_Priority_descriptor();
  }
  static inline const ::std::string& Priority_Name(Priority value) {
    return FrameGroupRequest_Priority_Name(value);
  }
  static inline bool Priority_Parse(const ::std::string& name,
      Priority* value) {
    return FrameGroupRequest_Priority_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required .Protocol.FrameGroupRequest.RequestType type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::Protocol::FrameGroupRequest_RequestType type() const;
  inline void set_type(::Protocol::FrameGroupRequest_RequestType value);
  
  // required string studyUid = 2;
  inline bool has_studyuid() const;
  inline void clear_studyuid();
  static const int kStudyUidFieldNumber = 2;
  inline const ::std::string& studyuid() const;
  inline void set_studyuid(const ::std::string& value);
  inline void set_studyuid(const char* value);
  inline void set_studyuid(const char* value, size_t size);
  inline ::std::string* mutable_studyuid();
  inline ::std::string* release_studyuid();
  
  // required uint32 studyUidNumber = 3;
  inline bool has_studyuidnumber() const;
  inline void clear_studyuidnumber();
  static const int kStudyUidNumberFieldNumber = 3;
  inline ::google::protobuf::uint32 studyuidnumber() const;
  inline void set_studyuidnumber(::google::protobuf::uint32 value);
  
  // required string seriesUid = 4;
  inline bool has_seriesuid() const;
  inline void clear_seriesuid();
  static const int kSeriesUidFieldNumber = 4;
  inline const ::std::string& seriesuid() const;
  inline void set_seriesuid(const ::std::string& value);
  inline void set_seriesuid(const char* value);
  inline void set_seriesuid(const char* value, size_t size);
  inline ::std::string* mutable_seriesuid();
  inline ::std::string* release_seriesuid();
  
  // required uint32 seriesUidNumber = 5;
  inline bool has_seriesuidnumber() const;
  inline void clear_seriesuidnumber();
  static const int kSeriesUidNumberFieldNumber = 5;
  inline ::google::protobuf::uint32 seriesuidnumber() const;
  inline void set_seriesuidnumber(::google::protobuf::uint32 value);
  
  // required .Protocol.FrameGroupRequest.Priority priority = 6;
  inline bool has_priority() const;
  inline void clear_priority();
  static const int kPriorityFieldNumber = 6;
  inline ::Protocol::FrameGroupRequest_Priority priority() const;
  inline void set_priority(::Protocol::FrameGroupRequest_Priority value);
  
  // required string instanceUidPrefix = 7;
  inline bool has_instanceuidprefix() const;
  inline void clear_instanceuidprefix();
  static const int kInstanceUidPrefixFieldNumber = 7;
  inline const ::std::string& instanceuidprefix() const;
  inline void set_instanceuidprefix(const ::std::string& value);
  inline void set_instanceuidprefix(const char* value);
  inline void set_instanceuidprefix(const char* value, size_t size);
  inline ::std::string* mutable_instanceuidprefix();
  inline ::std::string* release_instanceuidprefix();
  
  // repeated .Protocol.FrameRequest frames = 8;
  inline int frames_size() const;
  inline void clear_frames();
  static const int kFramesFieldNumber = 8;
  inline const ::Protocol::FrameRequest& frames(int index) const;
  inline ::Protocol::FrameRequest* mutable_frames(int index);
  inline ::Protocol::FrameRequest* add_frames();
  inline const ::google::protobuf::RepeatedPtrField< ::Protocol::FrameRequest >&
      frames() const;
  inline ::google::protobuf::RepeatedPtrField< ::Protocol::FrameRequest >*
      mutable_frames();
  
  // required bool multiFrame = 9;
  inline bool has_multiframe() const;
  inline void clear_multiframe();
  static const int kMultiFrameFieldNumber = 9;
  inline bool multiframe() const;
  inline void set_multiframe(bool value);
  
  // @@protoc_insertion_point(class_scope:Protocol.FrameGroupRequest)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_studyuid();
  inline void clear_has_studyuid();
  inline void set_has_studyuidnumber();
  inline void clear_has_studyuidnumber();
  inline void set_has_seriesuid();
  inline void clear_has_seriesuid();
  inline void set_has_seriesuidnumber();
  inline void clear_has_seriesuidnumber();
  inline void set_has_priority();
  inline void clear_has_priority();
  inline void set_has_instanceuidprefix();
  inline void clear_has_instanceuidprefix();
  inline void set_has_multiframe();
  inline void clear_has_multiframe();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* studyuid_;
  int type_;
  ::google::protobuf::uint32 studyuidnumber_;
  ::std::string* seriesuid_;
  ::google::protobuf::uint32 seriesuidnumber_;
  int priority_;
  ::std::string* instanceuidprefix_;
  ::google::protobuf::RepeatedPtrField< ::Protocol::FrameRequest > frames_;
  bool multiframe_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];
  
  friend void  protobuf_AddDesc_stream_2eproto();
  friend void protobuf_AssignDesc_stream_2eproto();
  friend void protobuf_ShutdownFile_stream_2eproto();
  
  void InitAsDefaultInstance();
  static FrameGroupRequest* default_instance_;
};
// -------------------------------------------------------------------

class FrameHeader : public ::google::protobuf::Message {
 public:
  FrameHeader();
  virtual ~FrameHeader();
  
  FrameHeader(const FrameHeader& from);
  
  inline FrameHeader& operator=(const FrameHeader& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FrameHeader& default_instance();
  
  void Swap(FrameHeader* other);
  
  // implements Message ----------------------------------------------
  
  FrameHeader* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FrameHeader& from);
  void MergeFrom(const FrameHeader& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef FrameHeader_bitDepth bitDepth;
  static const bitDepth depthU8 = FrameHeader_bitDepth_depthU8;
  static const bitDepth depthS8 = FrameHeader_bitDepth_depthS8;
  static const bitDepth depthU16 = FrameHeader_bitDepth_depthU16;
  static const bitDepth depthS16 = FrameHeader_bitDepth_depthS16;
  static const bitDepth depthU32 = FrameHeader_bitDepth_depthU32;
  static const bitDepth depthS32 = FrameHeader_bitDepth_depthS32;
  static inline bool bitDepth_IsValid(int value) {
    return FrameHeader_bitDepth_IsValid(value);
  }
  static const bitDepth bitDepth_MIN =
    FrameHeader_bitDepth_bitDepth_MIN;
  static const bitDepth bitDepth_MAX =
    FrameHeader_bitDepth_bitDepth_MAX;
  static const int bitDepth_ARRAYSIZE =
    FrameHeader_bitDepth_bitDepth_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  bitDepth_descriptor() {
    return FrameHeader_bitDepth_descriptor();
  }
  static inline const ::std::string& bitDepth_Name(bitDepth value) {
    return FrameHeader_bitDepth_Name(value);
  }
  static inline bool bitDepth_Parse(const ::std::string& name,
      bitDepth* value) {
    return FrameHeader_bitDepth_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required uint32 numberOfFrames = 1;
  inline bool has_numberofframes() const;
  inline void clear_numberofframes();
  static const int kNumberOfFramesFieldNumber = 1;
  inline ::google::protobuf::uint32 numberofframes() const;
  inline void set_numberofframes(::google::protobuf::uint32 value);
  
  // required uint32 imageSizeX = 2;
  inline bool has_imagesizex() const;
  inline void clear_imagesizex();
  static const int kImageSizeXFieldNumber = 2;
  inline ::google::protobuf::uint32 imagesizex() const;
  inline void set_imagesizex(::google::protobuf::uint32 value);
  
  // required uint32 imageSizeY = 3;
  inline bool has_imagesizey() const;
  inline void clear_imagesizey();
  static const int kImageSizeYFieldNumber = 3;
  inline ::google::protobuf::uint32 imagesizey() const;
  inline void set_imagesizey(::google::protobuf::uint32 value);
  
  // required .Protocol.FrameHeader.bitDepth depth = 4;
  inline bool has_depth() const;
  inline void clear_depth();
  static const int kDepthFieldNumber = 4;
  inline ::Protocol::FrameHeader_bitDepth depth() const;
  inline void set_depth(::Protocol::FrameHeader_bitDepth value);
  
  // required string colorSpace = 5;
  inline bool has_colorspace() const;
  inline void clear_colorspace();
  static const int kColorSpaceFieldNumber = 5;
  inline const ::std::string& colorspace() const;
  inline void set_colorspace(const ::std::string& value);
  inline void set_colorspace(const char* value);
  inline void set_colorspace(const char* value, size_t size);
  inline ::std::string* mutable_colorspace();
  inline ::std::string* release_colorspace();
  
  // required string transferSyntax = 6;
  inline bool has_transfersyntax() const;
  inline void clear_transfersyntax();
  static const int kTransferSyntaxFieldNumber = 6;
  inline const ::std::string& transfersyntax() const;
  inline void set_transfersyntax(const ::std::string& value);
  inline void set_transfersyntax(const char* value);
  inline void set_transfersyntax(const char* value, size_t size);
  inline ::std::string* mutable_transfersyntax();
  inline ::std::string* release_transfersyntax();
  
  // required uint32 channelsNumber = 7;
  inline bool has_channelsnumber() const;
  inline void clear_channelsnumber();
  static const int kChannelsNumberFieldNumber = 7;
  inline ::google::protobuf::uint32 channelsnumber() const;
  inline void set_channelsnumber(::google::protobuf::uint32 value);
  
  // required bool bInterleaved = 8;
  inline bool has_binterleaved() const;
  inline void clear_binterleaved();
  static const int kBInterleavedFieldNumber = 8;
  inline bool binterleaved() const;
  inline void set_binterleaved(bool value);
  
  // required bool b2Complement = 9;
  inline bool has_b2complement() const;
  inline void clear_b2complement();
  static const int kB2ComplementFieldNumber = 9;
  inline bool b2complement() const;
  inline void set_b2complement(bool value);
  
  // required uint32 allocatedBits = 10;
  inline bool has_allocatedbits() const;
  inline void clear_allocatedbits();
  static const int kAllocatedBitsFieldNumber = 10;
  inline ::google::protobuf::uint32 allocatedbits() const;
  inline void set_allocatedbits(::google::protobuf::uint32 value);
  
  // required uint32 storedBits = 11;
  inline bool has_storedbits() const;
  inline void clear_storedbits();
  static const int kStoredBitsFieldNumber = 11;
  inline ::google::protobuf::uint32 storedbits() const;
  inline void set_storedbits(::google::protobuf::uint32 value);
  
  // required uint32 highBit = 12;
  inline bool has_highbit() const;
  inline void clear_highbit();
  static const int kHighBitFieldNumber = 12;
  inline ::google::protobuf::uint32 highbit() const;
  inline void set_highbit(::google::protobuf::uint32 value);
  
  // required bool bSubSampledY = 13;
  inline bool has_bsubsampledy() const;
  inline void clear_bsubsampledy();
  static const int kBSubSampledYFieldNumber = 13;
  inline bool bsubsampledy() const;
  inline void set_bsubsampledy(bool value);
  
  // required bool bSubSampledX = 14;
  inline bool has_bsubsampledx() const;
  inline void clear_bsubsampledx();
  static const int kBSubSampledXFieldNumber = 14;
  inline bool bsubsampledx() const;
  inline void set_bsubsampledx(bool value);
  
  // @@protoc_insertion_point(class_scope:Protocol.FrameHeader)
 private:
  inline void set_has_numberofframes();
  inline void clear_has_numberofframes();
  inline void set_has_imagesizex();
  inline void clear_has_imagesizex();
  inline void set_has_imagesizey();
  inline void clear_has_imagesizey();
  inline void set_has_depth();
  inline void clear_has_depth();
  inline void set_has_colorspace();
  inline void clear_has_colorspace();
  inline void set_has_transfersyntax();
  inline void clear_has_transfersyntax();
  inline void set_has_channelsnumber();
  inline void clear_has_channelsnumber();
  inline void set_has_binterleaved();
  inline void clear_has_binterleaved();
  inline void set_has_b2complement();
  inline void clear_has_b2complement();
  inline void set_has_allocatedbits();
  inline void clear_has_allocatedbits();
  inline void set_has_storedbits();
  inline void clear_has_storedbits();
  inline void set_has_highbit();
  inline void clear_has_highbit();
  inline void set_has_bsubsampledy();
  inline void clear_has_bsubsampledy();
  inline void set_has_bsubsampledx();
  inline void clear_has_bsubsampledx();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 numberofframes_;
  ::google::protobuf::uint32 imagesizex_;
  ::google::protobuf::uint32 imagesizey_;
  int depth_;
  ::std::string* colorspace_;
  ::std::string* transfersyntax_;
  ::google::protobuf::uint32 channelsnumber_;
  ::google::protobuf::uint32 allocatedbits_;
  ::google::protobuf::uint32 storedbits_;
  bool binterleaved_;
  bool b2complement_;
  bool bsubsampledy_;
  bool bsubsampledx_;
  ::google::protobuf::uint32 highbit_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(14 + 31) / 32];
  
  friend void  protobuf_AddDesc_stream_2eproto();
  friend void protobuf_AssignDesc_stream_2eproto();
  friend void protobuf_ShutdownFile_stream_2eproto();
  
  void InitAsDefaultInstance();
  static FrameHeader* default_instance_;
};
// -------------------------------------------------------------------

class FrameResponse : public ::google::protobuf::Message {
 public:
  FrameResponse();
  virtual ~FrameResponse();
  
  FrameResponse(const FrameResponse& from);
  
  inline FrameResponse& operator=(const FrameResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FrameResponse& default_instance();
  
  void Swap(FrameResponse* other);
  
  // implements Message ----------------------------------------------
  
  FrameResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FrameResponse& from);
  void MergeFrom(const FrameResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .Protocol.FrameRequest frameRequest = 1;
  inline bool has_framerequest() const;
  inline void clear_framerequest();
  static const int kFrameRequestFieldNumber = 1;
  inline const ::Protocol::FrameRequest& framerequest() const;
  inline ::Protocol::FrameRequest* mutable_framerequest();
  inline ::Protocol::FrameRequest* release_framerequest();
  
  // @@protoc_insertion_point(class_scope:Protocol.FrameResponse)
 private:
  inline void set_has_framerequest();
  inline void clear_has_framerequest();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::Protocol::FrameRequest* framerequest_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_stream_2eproto();
  friend void protobuf_AssignDesc_stream_2eproto();
  friend void protobuf_ShutdownFile_stream_2eproto();
  
  void InitAsDefaultInstance();
  static FrameResponse* default_instance_;
};
// -------------------------------------------------------------------

class FrameFragment : public ::google::protobuf::Message {
 public:
  FrameFragment();
  virtual ~FrameFragment();
  
  FrameFragment(const FrameFragment& from);
  
  inline FrameFragment& operator=(const FrameFragment& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FrameFragment& default_instance();
  
  void Swap(FrameFragment* other);
  
  // implements Message ----------------------------------------------
  
  FrameFragment* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FrameFragment& from);
  void MergeFrom(const FrameFragment& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 offset = 1;
  inline bool has_offset() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 1;
  inline ::google::protobuf::uint32 offset() const;
  inline void set_offset(::google::protobuf::uint32 value);
  
  // required uint32 size = 2;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 2;
  inline ::google::protobuf::uint32 size() const;
  inline void set_size(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:Protocol.FrameFragment)
 private:
  inline void set_has_offset();
  inline void clear_has_offset();
  inline void set_has_size();
  inline void clear_has_size();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 offset_;
  ::google::protobuf::uint32 size_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_stream_2eproto();
  friend void protobuf_AssignDesc_stream_2eproto();
  friend void protobuf_ShutdownFile_stream_2eproto();
  
  void InitAsDefaultInstance();
  static FrameFragment* default_instance_;
};
// ===================================================================


// ===================================================================

// FrameRequest

// required string instanceUid = 1;
inline bool FrameRequest::has_instanceuid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FrameRequest::set_has_instanceuid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FrameRequest::clear_has_instanceuid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FrameRequest::clear_instanceuid() {
  if (instanceuid_ != &::google::protobuf::internal::kEmptyString) {
    instanceuid_->clear();
  }
  clear_has_instanceuid();
}
inline const ::std::string& FrameRequest::instanceuid() const {
  return *instanceuid_;
}
inline void FrameRequest::set_instanceuid(const ::std::string& value) {
  set_has_instanceuid();
  if (instanceuid_ == &::google::protobuf::internal::kEmptyString) {
    instanceuid_ = new ::std::string;
  }
  instanceuid_->assign(value);
}
inline void FrameRequest::set_instanceuid(const char* value) {
  set_has_instanceuid();
  if (instanceuid_ == &::google::protobuf::internal::kEmptyString) {
    instanceuid_ = new ::std::string;
  }
  instanceuid_->assign(value);
}
inline void FrameRequest::set_instanceuid(const char* value, size_t size) {
  set_has_instanceuid();
  if (instanceuid_ == &::google::protobuf::internal::kEmptyString) {
    instanceuid_ = new ::std::string;
  }
  instanceuid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* FrameRequest::mutable_instanceuid() {
  set_has_instanceuid();
  if (instanceuid_ == &::google::protobuf::internal::kEmptyString) {
    instanceuid_ = new ::std::string;
  }
  return instanceuid_;
}
inline ::std::string* FrameRequest::release_instanceuid() {
  clear_has_instanceuid();
  if (instanceuid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = instanceuid_;
    instanceuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required uint32 instanceUidNumber = 2;
inline bool FrameRequest::has_instanceuidnumber() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FrameRequest::set_has_instanceuidnumber() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FrameRequest::clear_has_instanceuidnumber() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FrameRequest::clear_instanceuidnumber() {
  instanceuidnumber_ = 0u;
  clear_has_instanceuidnumber();
}
inline ::google::protobuf::uint32 FrameRequest::instanceuidnumber() const {
  return instanceuidnumber_;
}
inline void FrameRequest::set_instanceuidnumber(::google::protobuf::uint32 value) {
  set_has_instanceuidnumber();
  instanceuidnumber_ = value;
}

// required uint32 frameNumber = 3;
inline bool FrameRequest::has_framenumber() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FrameRequest::set_has_framenumber() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FrameRequest::clear_has_framenumber() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void FrameRequest::clear_framenumber() {
  framenumber_ = 0u;
  clear_has_framenumber();
}
inline ::google::protobuf::uint32 FrameRequest::framenumber() const {
  return framenumber_;
}
inline void FrameRequest::set_framenumber(::google::protobuf::uint32 value) {
  set_has_framenumber();
  framenumber_ = value;
}

// -------------------------------------------------------------------

// FrameGroupRequest

// required .Protocol.FrameGroupRequest.RequestType type = 1;
inline bool FrameGroupRequest::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FrameGroupRequest::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FrameGroupRequest::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FrameGroupRequest::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::Protocol::FrameGroupRequest_RequestType FrameGroupRequest::type() const {
  return static_cast< ::Protocol::FrameGroupRequest_RequestType >(type_);
}
inline void FrameGroupRequest::set_type(::Protocol::FrameGroupRequest_RequestType value) {
  GOOGLE_DCHECK(::Protocol::FrameGroupRequest_RequestType_IsValid(value));
  set_has_type();
  type_ = value;
}

// required string studyUid = 2;
inline bool FrameGroupRequest::has_studyuid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FrameGroupRequest::set_has_studyuid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FrameGroupRequest::clear_has_studyuid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FrameGroupRequest::clear_studyuid() {
  if (studyuid_ != &::google::protobuf::internal::kEmptyString) {
    studyuid_->clear();
  }
  clear_has_studyuid();
}
inline const ::std::string& FrameGroupRequest::studyuid() const {
  return *studyuid_;
}
inline void FrameGroupRequest::set_studyuid(const ::std::string& value) {
  set_has_studyuid();
  if (studyuid_ == &::google::protobuf::internal::kEmptyString) {
    studyuid_ = new ::std::string;
  }
  studyuid_->assign(value);
}
inline void FrameGroupRequest::set_studyuid(const char* value) {
  set_has_studyuid();
  if (studyuid_ == &::google::protobuf::internal::kEmptyString) {
    studyuid_ = new ::std::string;
  }
  studyuid_->assign(value);
}
inline void FrameGroupRequest::set_studyuid(const char* value, size_t size) {
  set_has_studyuid();
  if (studyuid_ == &::google::protobuf::internal::kEmptyString) {
    studyuid_ = new ::std::string;
  }
  studyuid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* FrameGroupRequest::mutable_studyuid() {
  set_has_studyuid();
  if (studyuid_ == &::google::protobuf::internal::kEmptyString) {
    studyuid_ = new ::std::string;
  }
  return studyuid_;
}
inline ::std::string* FrameGroupRequest::release_studyuid() {
  clear_has_studyuid();
  if (studyuid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = studyuid_;
    studyuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required uint32 studyUidNumber = 3;
inline bool FrameGroupRequest::has_studyuidnumber() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FrameGroupRequest::set_has_studyuidnumber() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FrameGroupRequest::clear_has_studyuidnumber() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void FrameGroupRequest::clear_studyuidnumber() {
  studyuidnumber_ = 0u;
  clear_has_studyuidnumber();
}
inline ::google::protobuf::uint32 FrameGroupRequest::studyuidnumber() const {
  return studyuidnumber_;
}
inline void FrameGroupRequest::set_studyuidnumber(::google::protobuf::uint32 value) {
  set_has_studyuidnumber();
  studyuidnumber_ = value;
}

// required string seriesUid = 4;
inline bool FrameGroupRequest::has_seriesuid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void FrameGroupRequest::set_has_seriesuid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void FrameGroupRequest::clear_has_seriesuid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void FrameGroupRequest::clear_seriesuid() {
  if (seriesuid_ != &::google::protobuf::internal::kEmptyString) {
    seriesuid_->clear();
  }
  clear_has_seriesuid();
}
inline const ::std::string& FrameGroupRequest::seriesuid() const {
  return *seriesuid_;
}
inline void FrameGroupRequest::set_seriesuid(const ::std::string& value) {
  set_has_seriesuid();
  if (seriesuid_ == &::google::protobuf::internal::kEmptyString) {
    seriesuid_ = new ::std::string;
  }
  seriesuid_->assign(value);
}
inline void FrameGroupRequest::set_seriesuid(const char* value) {
  set_has_seriesuid();
  if (seriesuid_ == &::google::protobuf::internal::kEmptyString) {
    seriesuid_ = new ::std::string;
  }
  seriesuid_->assign(value);
}
inline void FrameGroupRequest::set_seriesuid(const char* value, size_t size) {
  set_has_seriesuid();
  if (seriesuid_ == &::google::protobuf::internal::kEmptyString) {
    seriesuid_ = new ::std::string;
  }
  seriesuid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* FrameGroupRequest::mutable_seriesuid() {
  set_has_seriesuid();
  if (seriesuid_ == &::google::protobuf::internal::kEmptyString) {
    seriesuid_ = new ::std::string;
  }
  return seriesuid_;
}
inline ::std::string* FrameGroupRequest::release_seriesuid() {
  clear_has_seriesuid();
  if (seriesuid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = seriesuid_;
    seriesuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required uint32 seriesUidNumber = 5;
inline bool FrameGroupRequest::has_seriesuidnumber() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void FrameGroupRequest::set_has_seriesuidnumber() {
  _has_bits_[0] |= 0x00000010u;
}
inline void FrameGroupRequest::clear_has_seriesuidnumber() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void FrameGroupRequest::clear_seriesuidnumber() {
  seriesuidnumber_ = 0u;
  clear_has_seriesuidnumber();
}
inline ::google::protobuf::uint32 FrameGroupRequest::seriesuidnumber() const {
  return seriesuidnumber_;
}
inline void FrameGroupRequest::set_seriesuidnumber(::google::protobuf::uint32 value) {
  set_has_seriesuidnumber();
  seriesuidnumber_ = value;
}

// required .Protocol.FrameGroupRequest.Priority priority = 6;
inline bool FrameGroupRequest::has_priority() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void FrameGroupRequest::set_has_priority() {
  _has_bits_[0] |= 0x00000020u;
}
inline void FrameGroupRequest::clear_has_priority() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void FrameGroupRequest::clear_priority() {
  priority_ = 0;
  clear_has_priority();
}
inline ::Protocol::FrameGroupRequest_Priority FrameGroupRequest::priority() const {
  return static_cast< ::Protocol::FrameGroupRequest_Priority >(priority_);
}
inline void FrameGroupRequest::set_priority(::Protocol::FrameGroupRequest_Priority value) {
  GOOGLE_DCHECK(::Protocol::FrameGroupRequest_Priority_IsValid(value));
  set_has_priority();
  priority_ = value;
}

// required string instanceUidPrefix = 7;
inline bool FrameGroupRequest::has_instanceuidprefix() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void FrameGroupRequest::set_has_instanceuidprefix() {
  _has_bits_[0] |= 0x00000040u;
}
inline void FrameGroupRequest::clear_has_instanceuidprefix() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void FrameGroupRequest::clear_instanceuidprefix() {
  if (instanceuidprefix_ != &::google::protobuf::internal::kEmptyString) {
    instanceuidprefix_->clear();
  }
  clear_has_instanceuidprefix();
}
inline const ::std::string& FrameGroupRequest::instanceuidprefix() const {
  return *instanceuidprefix_;
}
inline void FrameGroupRequest::set_instanceuidprefix(const ::std::string& value) {
  set_has_instanceuidprefix();
  if (instanceuidprefix_ == &::google::protobuf::internal::kEmptyString) {
    instanceuidprefix_ = new ::std::string;
  }
  instanceuidprefix_->assign(value);
}
inline void FrameGroupRequest::set_instanceuidprefix(const char* value) {
  set_has_instanceuidprefix();
  if (instanceuidprefix_ == &::google::protobuf::internal::kEmptyString) {
    instanceuidprefix_ = new ::std::string;
  }
  instanceuidprefix_->assign(value);
}
inline void FrameGroupRequest::set_instanceuidprefix(const char* value, size_t size) {
  set_has_instanceuidprefix();
  if (instanceuidprefix_ == &::google::protobuf::internal::kEmptyString) {
    instanceuidprefix_ = new ::std::string;
  }
  instanceuidprefix_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* FrameGroupRequest::mutable_instanceuidprefix() {
  set_has_instanceuidprefix();
  if (instanceuidprefix_ == &::google::protobuf::internal::kEmptyString) {
    instanceuidprefix_ = new ::std::string;
  }
  return instanceuidprefix_;
}
inline ::std::string* FrameGroupRequest::release_instanceuidprefix() {
  clear_has_instanceuidprefix();
  if (instanceuidprefix_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = instanceuidprefix_;
    instanceuidprefix_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// repeated .Protocol.FrameRequest frames = 8;
inline int FrameGroupRequest::frames_size() const {
  return frames_.size();
}
inline void FrameGroupRequest::clear_frames() {
  frames_.Clear();
}
inline const ::Protocol::FrameRequest& FrameGroupRequest::frames(int index) const {
  return frames_.Get(index);
}
inline ::Protocol::FrameRequest* FrameGroupRequest::mutable_frames(int index) {
  return frames_.Mutable(index);
}
inline ::Protocol::FrameRequest* FrameGroupRequest::add_frames() {
  return frames_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Protocol::FrameRequest >&
FrameGroupRequest::frames() const {
  return frames_;
}
inline ::google::protobuf::RepeatedPtrField< ::Protocol::FrameRequest >*
FrameGroupRequest::mutable_frames() {
  return &frames_;
}

// required bool multiFrame = 9;
inline bool FrameGroupRequest::has_multiframe() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void FrameGroupRequest::set_has_multiframe() {
  _has_bits_[0] |= 0x00000100u;
}
inline void FrameGroupRequest::clear_has_multiframe() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void FrameGroupRequest::clear_multiframe() {
  multiframe_ = false;
  clear_has_multiframe();
}
inline bool FrameGroupRequest::multiframe() const {
  return multiframe_;
}
inline void FrameGroupRequest::set_multiframe(bool value) {
  set_has_multiframe();
  multiframe_ = value;
}

// -------------------------------------------------------------------

// FrameHeader

// required uint32 numberOfFrames = 1;
inline bool FrameHeader::has_numberofframes() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FrameHeader::set_has_numberofframes() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FrameHeader::clear_has_numberofframes() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FrameHeader::clear_numberofframes() {
  numberofframes_ = 0u;
  clear_has_numberofframes();
}
inline ::google::protobuf::uint32 FrameHeader::numberofframes() const {
  return numberofframes_;
}
inline void FrameHeader::set_numberofframes(::google::protobuf::uint32 value) {
  set_has_numberofframes();
  numberofframes_ = value;
}

// required uint32 imageSizeX = 2;
inline bool FrameHeader::has_imagesizex() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FrameHeader::set_has_imagesizex() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FrameHeader::clear_has_imagesizex() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FrameHeader::clear_imagesizex() {
  imagesizex_ = 0u;
  clear_has_imagesizex();
}
inline ::google::protobuf::uint32 FrameHeader::imagesizex() const {
  return imagesizex_;
}
inline void FrameHeader::set_imagesizex(::google::protobuf::uint32 value) {
  set_has_imagesizex();
  imagesizex_ = value;
}

// required uint32 imageSizeY = 3;
inline bool FrameHeader::has_imagesizey() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FrameHeader::set_has_imagesizey() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FrameHeader::clear_has_imagesizey() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void FrameHeader::clear_imagesizey() {
  imagesizey_ = 0u;
  clear_has_imagesizey();
}
inline ::google::protobuf::uint32 FrameHeader::imagesizey() const {
  return imagesizey_;
}
inline void FrameHeader::set_imagesizey(::google::protobuf::uint32 value) {
  set_has_imagesizey();
  imagesizey_ = value;
}

// required .Protocol.FrameHeader.bitDepth depth = 4;
inline bool FrameHeader::has_depth() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void FrameHeader::set_has_depth() {
  _has_bits_[0] |= 0x00000008u;
}
inline void FrameHeader::clear_has_depth() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void FrameHeader::clear_depth() {
  depth_ = 0;
  clear_has_depth();
}
inline ::Protocol::FrameHeader_bitDepth FrameHeader::depth() const {
  return static_cast< ::Protocol::FrameHeader_bitDepth >(depth_);
}
inline void FrameHeader::set_depth(::Protocol::FrameHeader_bitDepth value) {
  GOOGLE_DCHECK(::Protocol::FrameHeader_bitDepth_IsValid(value));
  set_has_depth();
  depth_ = value;
}

// required string colorSpace = 5;
inline bool FrameHeader::has_colorspace() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void FrameHeader::set_has_colorspace() {
  _has_bits_[0] |= 0x00000010u;
}
inline void FrameHeader::clear_has_colorspace() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void FrameHeader::clear_colorspace() {
  if (colorspace_ != &::google::protobuf::internal::kEmptyString) {
    colorspace_->clear();
  }
  clear_has_colorspace();
}
inline const ::std::string& FrameHeader::colorspace() const {
  return *colorspace_;
}
inline void FrameHeader::set_colorspace(const ::std::string& value) {
  set_has_colorspace();
  if (colorspace_ == &::google::protobuf::internal::kEmptyString) {
    colorspace_ = new ::std::string;
  }
  colorspace_->assign(value);
}
inline void FrameHeader::set_colorspace(const char* value) {
  set_has_colorspace();
  if (colorspace_ == &::google::protobuf::internal::kEmptyString) {
    colorspace_ = new ::std::string;
  }
  colorspace_->assign(value);
}
inline void FrameHeader::set_colorspace(const char* value, size_t size) {
  set_has_colorspace();
  if (colorspace_ == &::google::protobuf::internal::kEmptyString) {
    colorspace_ = new ::std::string;
  }
  colorspace_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* FrameHeader::mutable_colorspace() {
  set_has_colorspace();
  if (colorspace_ == &::google::protobuf::internal::kEmptyString) {
    colorspace_ = new ::std::string;
  }
  return colorspace_;
}
inline ::std::string* FrameHeader::release_colorspace() {
  clear_has_colorspace();
  if (colorspace_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = colorspace_;
    colorspace_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required string transferSyntax = 6;
inline bool FrameHeader::has_transfersyntax() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void FrameHeader::set_has_transfersyntax() {
  _has_bits_[0] |= 0x00000020u;
}
inline void FrameHeader::clear_has_transfersyntax() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void FrameHeader::clear_transfersyntax() {
  if (transfersyntax_ != &::google::protobuf::internal::kEmptyString) {
    transfersyntax_->clear();
  }
  clear_has_transfersyntax();
}
inline const ::std::string& FrameHeader::transfersyntax() const {
  return *transfersyntax_;
}
inline void FrameHeader::set_transfersyntax(const ::std::string& value) {
  set_has_transfersyntax();
  if (transfersyntax_ == &::google::protobuf::internal::kEmptyString) {
    transfersyntax_ = new ::std::string;
  }
  transfersyntax_->assign(value);
}
inline void FrameHeader::set_transfersyntax(const char* value) {
  set_has_transfersyntax();
  if (transfersyntax_ == &::google::protobuf::internal::kEmptyString) {
    transfersyntax_ = new ::std::string;
  }
  transfersyntax_->assign(value);
}
inline void FrameHeader::set_transfersyntax(const char* value, size_t size) {
  set_has_transfersyntax();
  if (transfersyntax_ == &::google::protobuf::internal::kEmptyString) {
    transfersyntax_ = new ::std::string;
  }
  transfersyntax_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* FrameHeader::mutable_transfersyntax() {
  set_has_transfersyntax();
  if (transfersyntax_ == &::google::protobuf::internal::kEmptyString) {
    transfersyntax_ = new ::std::string;
  }
  return transfersyntax_;
}
inline ::std::string* FrameHeader::release_transfersyntax() {
  clear_has_transfersyntax();
  if (transfersyntax_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = transfersyntax_;
    transfersyntax_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required uint32 channelsNumber = 7;
inline bool FrameHeader::has_channelsnumber() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void FrameHeader::set_has_channelsnumber() {
  _has_bits_[0] |= 0x00000040u;
}
inline void FrameHeader::clear_has_channelsnumber() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void FrameHeader::clear_channelsnumber() {
  channelsnumber_ = 0u;
  clear_has_channelsnumber();
}
inline ::google::protobuf::uint32 FrameHeader::channelsnumber() const {
  return channelsnumber_;
}
inline void FrameHeader::set_channelsnumber(::google::protobuf::uint32 value) {
  set_has_channelsnumber();
  channelsnumber_ = value;
}

// required bool bInterleaved = 8;
inline bool FrameHeader::has_binterleaved() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void FrameHeader::set_has_binterleaved() {
  _has_bits_[0] |= 0x00000080u;
}
inline void FrameHeader::clear_has_binterleaved() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void FrameHeader::clear_binterleaved() {
  binterleaved_ = false;
  clear_has_binterleaved();
}
inline bool FrameHeader::binterleaved() const {
  return binterleaved_;
}
inline void FrameHeader::set_binterleaved(bool value) {
  set_has_binterleaved();
  binterleaved_ = value;
}

// required bool b2Complement = 9;
inline bool FrameHeader::has_b2complement() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void FrameHeader::set_has_b2complement() {
  _has_bits_[0] |= 0x00000100u;
}
inline void FrameHeader::clear_has_b2complement() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void FrameHeader::clear_b2complement() {
  b2complement_ = false;
  clear_has_b2complement();
}
inline bool FrameHeader::b2complement() const {
  return b2complement_;
}
inline void FrameHeader::set_b2complement(bool value) {
  set_has_b2complement();
  b2complement_ = value;
}

// required uint32 allocatedBits = 10;
inline bool FrameHeader::has_allocatedbits() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void FrameHeader::set_has_allocatedbits() {
  _has_bits_[0] |= 0x00000200u;
}
inline void FrameHeader::clear_has_allocatedbits() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void FrameHeader::clear_allocatedbits() {
  allocatedbits_ = 0u;
  clear_has_allocatedbits();
}
inline ::google::protobuf::uint32 FrameHeader::allocatedbits() const {
  return allocatedbits_;
}
inline void FrameHeader::set_allocatedbits(::google::protobuf::uint32 value) {
  set_has_allocatedbits();
  allocatedbits_ = value;
}

// required uint32 storedBits = 11;
inline bool FrameHeader::has_storedbits() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void FrameHeader::set_has_storedbits() {
  _has_bits_[0] |= 0x00000400u;
}
inline void FrameHeader::clear_has_storedbits() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void FrameHeader::clear_storedbits() {
  storedbits_ = 0u;
  clear_has_storedbits();
}
inline ::google::protobuf::uint32 FrameHeader::storedbits() const {
  return storedbits_;
}
inline void FrameHeader::set_storedbits(::google::protobuf::uint32 value) {
  set_has_storedbits();
  storedbits_ = value;
}

// required uint32 highBit = 12;
inline bool FrameHeader::has_highbit() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void FrameHeader::set_has_highbit() {
  _has_bits_[0] |= 0x00000800u;
}
inline void FrameHeader::clear_has_highbit() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void FrameHeader::clear_highbit() {
  highbit_ = 0u;
  clear_has_highbit();
}
inline ::google::protobuf::uint32 FrameHeader::highbit() const {
  return highbit_;
}
inline void FrameHeader::set_highbit(::google::protobuf::uint32 value) {
  set_has_highbit();
  highbit_ = value;
}

// required bool bSubSampledY = 13;
inline bool FrameHeader::has_bsubsampledy() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void FrameHeader::set_has_bsubsampledy() {
  _has_bits_[0] |= 0x00001000u;
}
inline void FrameHeader::clear_has_bsubsampledy() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void FrameHeader::clear_bsubsampledy() {
  bsubsampledy_ = false;
  clear_has_bsubsampledy();
}
inline bool FrameHeader::bsubsampledy() const {
  return bsubsampledy_;
}
inline void FrameHeader::set_bsubsampledy(bool value) {
  set_has_bsubsampledy();
  bsubsampledy_ = value;
}

// required bool bSubSampledX = 14;
inline bool FrameHeader::has_bsubsampledx() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void FrameHeader::set_has_bsubsampledx() {
  _has_bits_[0] |= 0x00002000u;
}
inline void FrameHeader::clear_has_bsubsampledx() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void FrameHeader::clear_bsubsampledx() {
  bsubsampledx_ = false;
  clear_has_bsubsampledx();
}
inline bool FrameHeader::bsubsampledx() const {
  return bsubsampledx_;
}
inline void FrameHeader::set_bsubsampledx(bool value) {
  set_has_bsubsampledx();
  bsubsampledx_ = value;
}

// -------------------------------------------------------------------

// FrameResponse

// required .Protocol.FrameRequest frameRequest = 1;
inline bool FrameResponse::has_framerequest() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FrameResponse::set_has_framerequest() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FrameResponse::clear_has_framerequest() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FrameResponse::clear_framerequest() {
  if (framerequest_ != NULL) framerequest_->::Protocol::FrameRequest::Clear();
  clear_has_framerequest();
}
inline const ::Protocol::FrameRequest& FrameResponse::framerequest() const {
  return framerequest_ != NULL ? *framerequest_ : *default_instance_->framerequest_;
}
inline ::Protocol::FrameRequest* FrameResponse::mutable_framerequest() {
  set_has_framerequest();
  if (framerequest_ == NULL) framerequest_ = new ::Protocol::FrameRequest;
  return framerequest_;
}
inline ::Protocol::FrameRequest* FrameResponse::release_framerequest() {
  clear_has_framerequest();
  ::Protocol::FrameRequest* temp = framerequest_;
  framerequest_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// FrameFragment

// required uint32 offset = 1;
inline bool FrameFragment::has_offset() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FrameFragment::set_has_offset() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FrameFragment::clear_has_offset() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FrameFragment::clear_offset() {
  offset_ = 0u;
  clear_has_offset();
}
inline ::google::protobuf::uint32 FrameFragment::offset() const {
  return offset_;
}
inline void FrameFragment::set_offset(::google::protobuf::uint32 value) {
  set_has_offset();
  offset_ = value;
}

// required uint32 size = 2;
inline bool FrameFragment::has_size() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FrameFragment::set_has_size() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FrameFragment::clear_has_size() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FrameFragment::clear_size() {
  size_ = 0u;
  clear_has_size();
}
inline ::google::protobuf::uint32 FrameFragment::size() const {
  return size_;
}
inline void FrameFragment::set_size(::google::protobuf::uint32 value) {
  set_has_size();
  size_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::FrameGroupRequest_RequestType>() {
  return ::Protocol::FrameGroupRequest_RequestType_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::FrameGroupRequest_Priority>() {
  return ::Protocol::FrameGroupRequest_Priority_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::FrameHeader_bitDepth>() {
  return ::Protocol::FrameHeader_bitDepth_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_stream_2eproto__INCLUDED
