// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

#ifndef PROTOBUF_stream_2eproto__INCLUDED
#define PROTOBUF_stream_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_stream_2eproto();
void protobuf_AssignDesc_stream_2eproto();
void protobuf_ShutdownFile_stream_2eproto();

class FrameRequest;
class SeriesRequest;
class FrameHeader;
class FrameResponse;
class FrameFragment;

enum SeriesRequest_RequestType {
  SeriesRequest_RequestType_Fetch = 0,
  SeriesRequest_RequestType_PriorityChanged = 1,
  SeriesRequest_RequestType_SetPrimaryFrame = 2,
  SeriesRequest_RequestType_Cancel = 3
};
bool SeriesRequest_RequestType_IsValid(int value);
const SeriesRequest_RequestType SeriesRequest_RequestType_RequestType_MIN = SeriesRequest_RequestType_Fetch;
const SeriesRequest_RequestType SeriesRequest_RequestType_RequestType_MAX = SeriesRequest_RequestType_Cancel;
const int SeriesRequest_RequestType_RequestType_ARRAYSIZE = SeriesRequest_RequestType_RequestType_MAX + 1;

const ::google::protobuf::EnumDescriptor* SeriesRequest_RequestType_descriptor();
inline const ::std::string& SeriesRequest_RequestType_Name(SeriesRequest_RequestType value) {
  return ::google::protobuf::internal::NameOfEnum(
    SeriesRequest_RequestType_descriptor(), value);
}
inline bool SeriesRequest_RequestType_Parse(
    const ::std::string& name, SeriesRequest_RequestType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SeriesRequest_RequestType>(
    SeriesRequest_RequestType_descriptor(), name, value);
}
enum SeriesRequest_Priority {
  SeriesRequest_Priority_Selected = 0,
  SeriesRequest_Priority_Visible = 1,
  SeriesRequest_Priority_Hidden = 2
};
bool SeriesRequest_Priority_IsValid(int value);
const SeriesRequest_Priority SeriesRequest_Priority_Priority_MIN = SeriesRequest_Priority_Selected;
const SeriesRequest_Priority SeriesRequest_Priority_Priority_MAX = SeriesRequest_Priority_Hidden;
const int SeriesRequest_Priority_Priority_ARRAYSIZE = SeriesRequest_Priority_Priority_MAX + 1;

const ::google::protobuf::EnumDescriptor* SeriesRequest_Priority_descriptor();
inline const ::std::string& SeriesRequest_Priority_Name(SeriesRequest_Priority value) {
  return ::google::protobuf::internal::NameOfEnum(
    SeriesRequest_Priority_descriptor(), value);
}
inline bool SeriesRequest_Priority_Parse(
    const ::std::string& name, SeriesRequest_Priority* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SeriesRequest_Priority>(
    SeriesRequest_Priority_descriptor(), name, value);
}
// ===================================================================

class FrameRequest : public ::google::protobuf::Message {
 public:
  FrameRequest();
  virtual ~FrameRequest();
  
  FrameRequest(const FrameRequest& from);
  
  inline FrameRequest& operator=(const FrameRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FrameRequest& default_instance();
  
  void Swap(FrameRequest* other);
  
  // implements Message ----------------------------------------------
  
  FrameRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FrameRequest& from);
  void MergeFrom(const FrameRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string instanceUid = 1;
  inline bool has_instanceuid() const;
  inline void clear_instanceuid();
  static const int kInstanceUidFieldNumber = 1;
  inline const ::std::string& instanceuid() const;
  inline void set_instanceuid(const ::std::string& value);
  inline void set_instanceuid(const char* value);
  inline void set_instanceuid(const char* value, size_t size);
  inline ::std::string* mutable_instanceuid();
  inline ::std::string* release_instanceuid();
  
  // required uint32 instanceUidNumber = 2;
  inline bool has_instanceuidnumber() const;
  inline void clear_instanceuidnumber();
  static const int kInstanceUidNumberFieldNumber = 2;
  inline ::google::protobuf::uint32 instanceuidnumber() const;
  inline void set_instanceuidnumber(::google::protobuf::uint32 value);
  
  // required uint32 frameNumber = 3;
  inline bool has_framenumber() const;
  inline void clear_framenumber();
  static const int kFrameNumberFieldNumber = 3;
  inline ::google::protobuf::uint32 framenumber() const;
  inline void set_framenumber(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:Protocol.FrameRequest)
 private:
  inline void set_has_instanceuid();
  inline void clear_has_instanceuid();
  inline void set_has_instanceuidnumber();
  inline void clear_has_instanceuidnumber();
  inline void set_has_framenumber();
  inline void clear_has_framenumber();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* instanceuid_;
  ::google::protobuf::uint32 instanceuidnumber_;
  ::google::protobuf::uint32 framenumber_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_stream_2eproto();
  friend void protobuf_AssignDesc_stream_2eproto();
  friend void protobuf_ShutdownFile_stream_2eproto();
  
  void InitAsDefaultInstance();
  static FrameRequest* default_instance_;
};
// -------------------------------------------------------------------

class SeriesRequest : public ::google::protobuf::Message {
 public:
  SeriesRequest();
  virtual ~SeriesRequest();
  
  SeriesRequest(const SeriesRequest& from);
  
  inline SeriesRequest& operator=(const SeriesRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SeriesRequest& default_instance();
  
  void Swap(SeriesRequest* other);
  
  // implements Message ----------------------------------------------
  
  SeriesRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SeriesRequest& from);
  void MergeFrom(const SeriesRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef SeriesRequest_RequestType RequestType;
  static const RequestType Fetch = SeriesRequest_RequestType_Fetch;
  static const RequestType PriorityChanged = SeriesRequest_RequestType_PriorityChanged;
  static const RequestType SetPrimaryFrame = SeriesRequest_RequestType_SetPrimaryFrame;
  static const RequestType Cancel = SeriesRequest_RequestType_Cancel;
  static inline bool RequestType_IsValid(int value) {
    return SeriesRequest_RequestType_IsValid(value);
  }
  static const RequestType RequestType_MIN =
    SeriesRequest_RequestType_RequestType_MIN;
  static const RequestType RequestType_MAX =
    SeriesRequest_RequestType_RequestType_MAX;
  static const int RequestType_ARRAYSIZE =
    SeriesRequest_RequestType_RequestType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RequestType_descriptor() {
    return SeriesRequest_RequestType_descriptor();
  }
  static inline const ::std::string& RequestType_Name(RequestType value) {
    return SeriesRequest_RequestType_Name(value);
  }
  static inline bool RequestType_Parse(const ::std::string& name,
      RequestType* value) {
    return SeriesRequest_RequestType_Parse(name, value);
  }
  
  typedef SeriesRequest_Priority Priority;
  static const Priority Selected = SeriesRequest_Priority_Selected;
  static const Priority Visible = SeriesRequest_Priority_Visible;
  static const Priority Hidden = SeriesRequest_Priority_Hidden;
  static inline bool Priority_IsValid(int value) {
    return SeriesRequest_Priority_IsValid(value);
  }
  static const Priority Priority_MIN =
    SeriesRequest_Priority_Priority_MIN;
  static const Priority Priority_MAX =
    SeriesRequest_Priority_Priority_MAX;
  static const int Priority_ARRAYSIZE =
    SeriesRequest_Priority_Priority_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Priority_descriptor() {
    return SeriesRequest_Priority_descriptor();
  }
  static inline const ::std::string& Priority_Name(Priority value) {
    return SeriesRequest_Priority_Name(value);
  }
  static inline bool Priority_Parse(const ::std::string& name,
      Priority* value) {
    return SeriesRequest_Priority_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required .Protocol.SeriesRequest.RequestType type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::Protocol::SeriesRequest_RequestType type() const;
  inline void set_type(::Protocol::SeriesRequest_RequestType value);
  
  // required string studyUid = 2;
  inline bool has_studyuid() const;
  inline void clear_studyuid();
  static const int kStudyUidFieldNumber = 2;
  inline const ::std::string& studyuid() const;
  inline void set_studyuid(const ::std::string& value);
  inline void set_studyuid(const char* value);
  inline void set_studyuid(const char* value, size_t size);
  inline ::std::string* mutable_studyuid();
  inline ::std::string* release_studyuid();
  
  // required uint32 studyUidNumber = 3;
  inline bool has_studyuidnumber() const;
  inline void clear_studyuidnumber();
  static const int kStudyUidNumberFieldNumber = 3;
  inline ::google::protobuf::uint32 studyuidnumber() const;
  inline void set_studyuidnumber(::google::protobuf::uint32 value);
  
  // required string seriesUid = 4;
  inline bool has_seriesuid() const;
  inline void clear_seriesuid();
  static const int kSeriesUidFieldNumber = 4;
  inline const ::std::string& seriesuid() const;
  inline void set_seriesuid(const ::std::string& value);
  inline void set_seriesuid(const char* value);
  inline void set_seriesuid(const char* value, size_t size);
  inline ::std::string* mutable_seriesuid();
  inline ::std::string* release_seriesuid();
  
  // required uint32 seriesUidNumber = 5;
  inline bool has_seriesuidnumber() const;
  inline void clear_seriesuidnumber();
  static const int kSeriesUidNumberFieldNumber = 5;
  inline ::google::protobuf::uint32 seriesuidnumber() const;
  inline void set_seriesuidnumber(::google::protobuf::uint32 value);
  
  // required .Protocol.SeriesRequest.Priority priority = 6;
  inline bool has_priority() const;
  inline void clear_priority();
  static const int kPriorityFieldNumber = 6;
  inline ::Protocol::SeriesRequest_Priority priority() const;
  inline void set_priority(::Protocol::SeriesRequest_Priority value);
  
  // required string instanceUidPrefix = 7;
  inline bool has_instanceuidprefix() const;
  inline void clear_instanceuidprefix();
  static const int kInstanceUidPrefixFieldNumber = 7;
  inline const ::std::string& instanceuidprefix() const;
  inline void set_instanceuidprefix(const ::std::string& value);
  inline void set_instanceuidprefix(const char* value);
  inline void set_instanceuidprefix(const char* value, size_t size);
  inline ::std::string* mutable_instanceuidprefix();
  inline ::std::string* release_instanceuidprefix();
  
  // repeated .Protocol.FrameRequest frames = 8;
  inline int frames_size() const;
  inline void clear_frames();
  static const int kFramesFieldNumber = 8;
  inline const ::Protocol::FrameRequest& frames(int index) const;
  inline ::Protocol::FrameRequest* mutable_frames(int index);
  inline ::Protocol::FrameRequest* add_frames();
  inline const ::google::protobuf::RepeatedPtrField< ::Protocol::FrameRequest >&
      frames() const;
  inline ::google::protobuf::RepeatedPtrField< ::Protocol::FrameRequest >*
      mutable_frames();
  
  // @@protoc_insertion_point(class_scope:Protocol.SeriesRequest)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_studyuid();
  inline void clear_has_studyuid();
  inline void set_has_studyuidnumber();
  inline void clear_has_studyuidnumber();
  inline void set_has_seriesuid();
  inline void clear_has_seriesuid();
  inline void set_has_seriesuidnumber();
  inline void clear_has_seriesuidnumber();
  inline void set_has_priority();
  inline void clear_has_priority();
  inline void set_has_instanceuidprefix();
  inline void clear_has_instanceuidprefix();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* studyuid_;
  int type_;
  ::google::protobuf::uint32 studyuidnumber_;
  ::std::string* seriesuid_;
  ::google::protobuf::uint32 seriesuidnumber_;
  int priority_;
  ::std::string* instanceuidprefix_;
  ::google::protobuf::RepeatedPtrField< ::Protocol::FrameRequest > frames_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];
  
  friend void  protobuf_AddDesc_stream_2eproto();
  friend void protobuf_AssignDesc_stream_2eproto();
  friend void protobuf_ShutdownFile_stream_2eproto();
  
  void InitAsDefaultInstance();
  static SeriesRequest* default_instance_;
};
// -------------------------------------------------------------------

class FrameHeader : public ::google::protobuf::Message {
 public:
  FrameHeader();
  virtual ~FrameHeader();
  
  FrameHeader(const FrameHeader& from);
  
  inline FrameHeader& operator=(const FrameHeader& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FrameHeader& default_instance();
  
  void Swap(FrameHeader* other);
  
  // implements Message ----------------------------------------------
  
  FrameHeader* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FrameHeader& from);
  void MergeFrom(const FrameHeader& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 pixelDataSize = 1;
  inline bool has_pixeldatasize() const;
  inline void clear_pixeldatasize();
  static const int kPixelDataSizeFieldNumber = 1;
  inline ::google::protobuf::uint32 pixeldatasize() const;
  inline void set_pixeldatasize(::google::protobuf::uint32 value);
  
  // required uint32 width = 2;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 2;
  inline ::google::protobuf::uint32 width() const;
  inline void set_width(::google::protobuf::uint32 value);
  
  // required uint32 height = 3;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 3;
  inline ::google::protobuf::uint32 height() const;
  inline void set_height(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:Protocol.FrameHeader)
 private:
  inline void set_has_pixeldatasize();
  inline void clear_has_pixeldatasize();
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_height();
  inline void clear_has_height();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 pixeldatasize_;
  ::google::protobuf::uint32 width_;
  ::google::protobuf::uint32 height_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_stream_2eproto();
  friend void protobuf_AssignDesc_stream_2eproto();
  friend void protobuf_ShutdownFile_stream_2eproto();
  
  void InitAsDefaultInstance();
  static FrameHeader* default_instance_;
};
// -------------------------------------------------------------------

class FrameResponse : public ::google::protobuf::Message {
 public:
  FrameResponse();
  virtual ~FrameResponse();
  
  FrameResponse(const FrameResponse& from);
  
  inline FrameResponse& operator=(const FrameResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FrameResponse& default_instance();
  
  void Swap(FrameResponse* other);
  
  // implements Message ----------------------------------------------
  
  FrameResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FrameResponse& from);
  void MergeFrom(const FrameResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .Protocol.FrameRequest frameRequest = 1;
  inline bool has_framerequest() const;
  inline void clear_framerequest();
  static const int kFrameRequestFieldNumber = 1;
  inline const ::Protocol::FrameRequest& framerequest() const;
  inline ::Protocol::FrameRequest* mutable_framerequest();
  inline ::Protocol::FrameRequest* release_framerequest();
  
  // required .Protocol.FrameHeader frameHeader = 2;
  inline bool has_frameheader() const;
  inline void clear_frameheader();
  static const int kFrameHeaderFieldNumber = 2;
  inline const ::Protocol::FrameHeader& frameheader() const;
  inline ::Protocol::FrameHeader* mutable_frameheader();
  inline ::Protocol::FrameHeader* release_frameheader();
  
  // @@protoc_insertion_point(class_scope:Protocol.FrameResponse)
 private:
  inline void set_has_framerequest();
  inline void clear_has_framerequest();
  inline void set_has_frameheader();
  inline void clear_has_frameheader();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::Protocol::FrameRequest* framerequest_;
  ::Protocol::FrameHeader* frameheader_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_stream_2eproto();
  friend void protobuf_AssignDesc_stream_2eproto();
  friend void protobuf_ShutdownFile_stream_2eproto();
  
  void InitAsDefaultInstance();
  static FrameResponse* default_instance_;
};
// -------------------------------------------------------------------

class FrameFragment : public ::google::protobuf::Message {
 public:
  FrameFragment();
  virtual ~FrameFragment();
  
  FrameFragment(const FrameFragment& from);
  
  inline FrameFragment& operator=(const FrameFragment& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FrameFragment& default_instance();
  
  void Swap(FrameFragment* other);
  
  // implements Message ----------------------------------------------
  
  FrameFragment* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FrameFragment& from);
  void MergeFrom(const FrameFragment& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 offset = 1;
  inline bool has_offset() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 1;
  inline ::google::protobuf::uint32 offset() const;
  inline void set_offset(::google::protobuf::uint32 value);
  
  // required uint32 size = 2;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 2;
  inline ::google::protobuf::uint32 size() const;
  inline void set_size(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:Protocol.FrameFragment)
 private:
  inline void set_has_offset();
  inline void clear_has_offset();
  inline void set_has_size();
  inline void clear_has_size();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 offset_;
  ::google::protobuf::uint32 size_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_stream_2eproto();
  friend void protobuf_AssignDesc_stream_2eproto();
  friend void protobuf_ShutdownFile_stream_2eproto();
  
  void InitAsDefaultInstance();
  static FrameFragment* default_instance_;
};
// ===================================================================


// ===================================================================

// FrameRequest

// required string instanceUid = 1;
inline bool FrameRequest::has_instanceuid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FrameRequest::set_has_instanceuid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FrameRequest::clear_has_instanceuid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FrameRequest::clear_instanceuid() {
  if (instanceuid_ != &::google::protobuf::internal::kEmptyString) {
    instanceuid_->clear();
  }
  clear_has_instanceuid();
}
inline const ::std::string& FrameRequest::instanceuid() const {
  return *instanceuid_;
}
inline void FrameRequest::set_instanceuid(const ::std::string& value) {
  set_has_instanceuid();
  if (instanceuid_ == &::google::protobuf::internal::kEmptyString) {
    instanceuid_ = new ::std::string;
  }
  instanceuid_->assign(value);
}
inline void FrameRequest::set_instanceuid(const char* value) {
  set_has_instanceuid();
  if (instanceuid_ == &::google::protobuf::internal::kEmptyString) {
    instanceuid_ = new ::std::string;
  }
  instanceuid_->assign(value);
}
inline void FrameRequest::set_instanceuid(const char* value, size_t size) {
  set_has_instanceuid();
  if (instanceuid_ == &::google::protobuf::internal::kEmptyString) {
    instanceuid_ = new ::std::string;
  }
  instanceuid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* FrameRequest::mutable_instanceuid() {
  set_has_instanceuid();
  if (instanceuid_ == &::google::protobuf::internal::kEmptyString) {
    instanceuid_ = new ::std::string;
  }
  return instanceuid_;
}
inline ::std::string* FrameRequest::release_instanceuid() {
  clear_has_instanceuid();
  if (instanceuid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = instanceuid_;
    instanceuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required uint32 instanceUidNumber = 2;
inline bool FrameRequest::has_instanceuidnumber() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FrameRequest::set_has_instanceuidnumber() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FrameRequest::clear_has_instanceuidnumber() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FrameRequest::clear_instanceuidnumber() {
  instanceuidnumber_ = 0u;
  clear_has_instanceuidnumber();
}
inline ::google::protobuf::uint32 FrameRequest::instanceuidnumber() const {
  return instanceuidnumber_;
}
inline void FrameRequest::set_instanceuidnumber(::google::protobuf::uint32 value) {
  set_has_instanceuidnumber();
  instanceuidnumber_ = value;
}

// required uint32 frameNumber = 3;
inline bool FrameRequest::has_framenumber() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FrameRequest::set_has_framenumber() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FrameRequest::clear_has_framenumber() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void FrameRequest::clear_framenumber() {
  framenumber_ = 0u;
  clear_has_framenumber();
}
inline ::google::protobuf::uint32 FrameRequest::framenumber() const {
  return framenumber_;
}
inline void FrameRequest::set_framenumber(::google::protobuf::uint32 value) {
  set_has_framenumber();
  framenumber_ = value;
}

// -------------------------------------------------------------------

// SeriesRequest

// required .Protocol.SeriesRequest.RequestType type = 1;
inline bool SeriesRequest::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SeriesRequest::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SeriesRequest::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SeriesRequest::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::Protocol::SeriesRequest_RequestType SeriesRequest::type() const {
  return static_cast< ::Protocol::SeriesRequest_RequestType >(type_);
}
inline void SeriesRequest::set_type(::Protocol::SeriesRequest_RequestType value) {
  GOOGLE_DCHECK(::Protocol::SeriesRequest_RequestType_IsValid(value));
  set_has_type();
  type_ = value;
}

// required string studyUid = 2;
inline bool SeriesRequest::has_studyuid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SeriesRequest::set_has_studyuid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SeriesRequest::clear_has_studyuid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SeriesRequest::clear_studyuid() {
  if (studyuid_ != &::google::protobuf::internal::kEmptyString) {
    studyuid_->clear();
  }
  clear_has_studyuid();
}
inline const ::std::string& SeriesRequest::studyuid() const {
  return *studyuid_;
}
inline void SeriesRequest::set_studyuid(const ::std::string& value) {
  set_has_studyuid();
  if (studyuid_ == &::google::protobuf::internal::kEmptyString) {
    studyuid_ = new ::std::string;
  }
  studyuid_->assign(value);
}
inline void SeriesRequest::set_studyuid(const char* value) {
  set_has_studyuid();
  if (studyuid_ == &::google::protobuf::internal::kEmptyString) {
    studyuid_ = new ::std::string;
  }
  studyuid_->assign(value);
}
inline void SeriesRequest::set_studyuid(const char* value, size_t size) {
  set_has_studyuid();
  if (studyuid_ == &::google::protobuf::internal::kEmptyString) {
    studyuid_ = new ::std::string;
  }
  studyuid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SeriesRequest::mutable_studyuid() {
  set_has_studyuid();
  if (studyuid_ == &::google::protobuf::internal::kEmptyString) {
    studyuid_ = new ::std::string;
  }
  return studyuid_;
}
inline ::std::string* SeriesRequest::release_studyuid() {
  clear_has_studyuid();
  if (studyuid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = studyuid_;
    studyuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required uint32 studyUidNumber = 3;
inline bool SeriesRequest::has_studyuidnumber() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SeriesRequest::set_has_studyuidnumber() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SeriesRequest::clear_has_studyuidnumber() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SeriesRequest::clear_studyuidnumber() {
  studyuidnumber_ = 0u;
  clear_has_studyuidnumber();
}
inline ::google::protobuf::uint32 SeriesRequest::studyuidnumber() const {
  return studyuidnumber_;
}
inline void SeriesRequest::set_studyuidnumber(::google::protobuf::uint32 value) {
  set_has_studyuidnumber();
  studyuidnumber_ = value;
}

// required string seriesUid = 4;
inline bool SeriesRequest::has_seriesuid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SeriesRequest::set_has_seriesuid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SeriesRequest::clear_has_seriesuid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SeriesRequest::clear_seriesuid() {
  if (seriesuid_ != &::google::protobuf::internal::kEmptyString) {
    seriesuid_->clear();
  }
  clear_has_seriesuid();
}
inline const ::std::string& SeriesRequest::seriesuid() const {
  return *seriesuid_;
}
inline void SeriesRequest::set_seriesuid(const ::std::string& value) {
  set_has_seriesuid();
  if (seriesuid_ == &::google::protobuf::internal::kEmptyString) {
    seriesuid_ = new ::std::string;
  }
  seriesuid_->assign(value);
}
inline void SeriesRequest::set_seriesuid(const char* value) {
  set_has_seriesuid();
  if (seriesuid_ == &::google::protobuf::internal::kEmptyString) {
    seriesuid_ = new ::std::string;
  }
  seriesuid_->assign(value);
}
inline void SeriesRequest::set_seriesuid(const char* value, size_t size) {
  set_has_seriesuid();
  if (seriesuid_ == &::google::protobuf::internal::kEmptyString) {
    seriesuid_ = new ::std::string;
  }
  seriesuid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SeriesRequest::mutable_seriesuid() {
  set_has_seriesuid();
  if (seriesuid_ == &::google::protobuf::internal::kEmptyString) {
    seriesuid_ = new ::std::string;
  }
  return seriesuid_;
}
inline ::std::string* SeriesRequest::release_seriesuid() {
  clear_has_seriesuid();
  if (seriesuid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = seriesuid_;
    seriesuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required uint32 seriesUidNumber = 5;
inline bool SeriesRequest::has_seriesuidnumber() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SeriesRequest::set_has_seriesuidnumber() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SeriesRequest::clear_has_seriesuidnumber() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SeriesRequest::clear_seriesuidnumber() {
  seriesuidnumber_ = 0u;
  clear_has_seriesuidnumber();
}
inline ::google::protobuf::uint32 SeriesRequest::seriesuidnumber() const {
  return seriesuidnumber_;
}
inline void SeriesRequest::set_seriesuidnumber(::google::protobuf::uint32 value) {
  set_has_seriesuidnumber();
  seriesuidnumber_ = value;
}

// required .Protocol.SeriesRequest.Priority priority = 6;
inline bool SeriesRequest::has_priority() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SeriesRequest::set_has_priority() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SeriesRequest::clear_has_priority() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SeriesRequest::clear_priority() {
  priority_ = 0;
  clear_has_priority();
}
inline ::Protocol::SeriesRequest_Priority SeriesRequest::priority() const {
  return static_cast< ::Protocol::SeriesRequest_Priority >(priority_);
}
inline void SeriesRequest::set_priority(::Protocol::SeriesRequest_Priority value) {
  GOOGLE_DCHECK(::Protocol::SeriesRequest_Priority_IsValid(value));
  set_has_priority();
  priority_ = value;
}

// required string instanceUidPrefix = 7;
inline bool SeriesRequest::has_instanceuidprefix() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void SeriesRequest::set_has_instanceuidprefix() {
  _has_bits_[0] |= 0x00000040u;
}
inline void SeriesRequest::clear_has_instanceuidprefix() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void SeriesRequest::clear_instanceuidprefix() {
  if (instanceuidprefix_ != &::google::protobuf::internal::kEmptyString) {
    instanceuidprefix_->clear();
  }
  clear_has_instanceuidprefix();
}
inline const ::std::string& SeriesRequest::instanceuidprefix() const {
  return *instanceuidprefix_;
}
inline void SeriesRequest::set_instanceuidprefix(const ::std::string& value) {
  set_has_instanceuidprefix();
  if (instanceuidprefix_ == &::google::protobuf::internal::kEmptyString) {
    instanceuidprefix_ = new ::std::string;
  }
  instanceuidprefix_->assign(value);
}
inline void SeriesRequest::set_instanceuidprefix(const char* value) {
  set_has_instanceuidprefix();
  if (instanceuidprefix_ == &::google::protobuf::internal::kEmptyString) {
    instanceuidprefix_ = new ::std::string;
  }
  instanceuidprefix_->assign(value);
}
inline void SeriesRequest::set_instanceuidprefix(const char* value, size_t size) {
  set_has_instanceuidprefix();
  if (instanceuidprefix_ == &::google::protobuf::internal::kEmptyString) {
    instanceuidprefix_ = new ::std::string;
  }
  instanceuidprefix_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SeriesRequest::mutable_instanceuidprefix() {
  set_has_instanceuidprefix();
  if (instanceuidprefix_ == &::google::protobuf::internal::kEmptyString) {
    instanceuidprefix_ = new ::std::string;
  }
  return instanceuidprefix_;
}
inline ::std::string* SeriesRequest::release_instanceuidprefix() {
  clear_has_instanceuidprefix();
  if (instanceuidprefix_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = instanceuidprefix_;
    instanceuidprefix_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// repeated .Protocol.FrameRequest frames = 8;
inline int SeriesRequest::frames_size() const {
  return frames_.size();
}
inline void SeriesRequest::clear_frames() {
  frames_.Clear();
}
inline const ::Protocol::FrameRequest& SeriesRequest::frames(int index) const {
  return frames_.Get(index);
}
inline ::Protocol::FrameRequest* SeriesRequest::mutable_frames(int index) {
  return frames_.Mutable(index);
}
inline ::Protocol::FrameRequest* SeriesRequest::add_frames() {
  return frames_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Protocol::FrameRequest >&
SeriesRequest::frames() const {
  return frames_;
}
inline ::google::protobuf::RepeatedPtrField< ::Protocol::FrameRequest >*
SeriesRequest::mutable_frames() {
  return &frames_;
}

// -------------------------------------------------------------------

// FrameHeader

// required uint32 pixelDataSize = 1;
inline bool FrameHeader::has_pixeldatasize() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FrameHeader::set_has_pixeldatasize() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FrameHeader::clear_has_pixeldatasize() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FrameHeader::clear_pixeldatasize() {
  pixeldatasize_ = 0u;
  clear_has_pixeldatasize();
}
inline ::google::protobuf::uint32 FrameHeader::pixeldatasize() const {
  return pixeldatasize_;
}
inline void FrameHeader::set_pixeldatasize(::google::protobuf::uint32 value) {
  set_has_pixeldatasize();
  pixeldatasize_ = value;
}

// required uint32 width = 2;
inline bool FrameHeader::has_width() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FrameHeader::set_has_width() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FrameHeader::clear_has_width() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FrameHeader::clear_width() {
  width_ = 0u;
  clear_has_width();
}
inline ::google::protobuf::uint32 FrameHeader::width() const {
  return width_;
}
inline void FrameHeader::set_width(::google::protobuf::uint32 value) {
  set_has_width();
  width_ = value;
}

// required uint32 height = 3;
inline bool FrameHeader::has_height() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FrameHeader::set_has_height() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FrameHeader::clear_has_height() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void FrameHeader::clear_height() {
  height_ = 0u;
  clear_has_height();
}
inline ::google::protobuf::uint32 FrameHeader::height() const {
  return height_;
}
inline void FrameHeader::set_height(::google::protobuf::uint32 value) {
  set_has_height();
  height_ = value;
}

// -------------------------------------------------------------------

// FrameResponse

// required .Protocol.FrameRequest frameRequest = 1;
inline bool FrameResponse::has_framerequest() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FrameResponse::set_has_framerequest() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FrameResponse::clear_has_framerequest() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FrameResponse::clear_framerequest() {
  if (framerequest_ != NULL) framerequest_->::Protocol::FrameRequest::Clear();
  clear_has_framerequest();
}
inline const ::Protocol::FrameRequest& FrameResponse::framerequest() const {
  return framerequest_ != NULL ? *framerequest_ : *default_instance_->framerequest_;
}
inline ::Protocol::FrameRequest* FrameResponse::mutable_framerequest() {
  set_has_framerequest();
  if (framerequest_ == NULL) framerequest_ = new ::Protocol::FrameRequest;
  return framerequest_;
}
inline ::Protocol::FrameRequest* FrameResponse::release_framerequest() {
  clear_has_framerequest();
  ::Protocol::FrameRequest* temp = framerequest_;
  framerequest_ = NULL;
  return temp;
}

// required .Protocol.FrameHeader frameHeader = 2;
inline bool FrameResponse::has_frameheader() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FrameResponse::set_has_frameheader() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FrameResponse::clear_has_frameheader() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FrameResponse::clear_frameheader() {
  if (frameheader_ != NULL) frameheader_->::Protocol::FrameHeader::Clear();
  clear_has_frameheader();
}
inline const ::Protocol::FrameHeader& FrameResponse::frameheader() const {
  return frameheader_ != NULL ? *frameheader_ : *default_instance_->frameheader_;
}
inline ::Protocol::FrameHeader* FrameResponse::mutable_frameheader() {
  set_has_frameheader();
  if (frameheader_ == NULL) frameheader_ = new ::Protocol::FrameHeader;
  return frameheader_;
}
inline ::Protocol::FrameHeader* FrameResponse::release_frameheader() {
  clear_has_frameheader();
  ::Protocol::FrameHeader* temp = frameheader_;
  frameheader_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// FrameFragment

// required uint32 offset = 1;
inline bool FrameFragment::has_offset() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FrameFragment::set_has_offset() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FrameFragment::clear_has_offset() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FrameFragment::clear_offset() {
  offset_ = 0u;
  clear_has_offset();
}
inline ::google::protobuf::uint32 FrameFragment::offset() const {
  return offset_;
}
inline void FrameFragment::set_offset(::google::protobuf::uint32 value) {
  set_has_offset();
  offset_ = value;
}

// required uint32 size = 2;
inline bool FrameFragment::has_size() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FrameFragment::set_has_size() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FrameFragment::clear_has_size() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FrameFragment::clear_size() {
  size_ = 0u;
  clear_has_size();
}
inline ::google::protobuf::uint32 FrameFragment::size() const {
  return size_;
}
inline void FrameFragment::set_size(::google::protobuf::uint32 value) {
  set_has_size();
  size_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::SeriesRequest_RequestType>() {
  return ::Protocol::SeriesRequest_RequestType_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::SeriesRequest_Priority>() {
  return ::Protocol::SeriesRequest_Priority_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_stream_2eproto__INCLUDED
